### ISSUE TITLE
Why Yale CAS 2.0?

### ISSUE THREAD

**Issue by iyee** [t3hmrman/casgo#24]
Yale CAS had became a project of Jasig since 2004 and the 3.0 spec released earlier: https://github.com/Jasig/cas/blob/master/cas-server-documentation/protocol/CAS-Protocol-Specification.md

So why not making this repo up to date?

**Comment by t3hmrman** [comment]
Casgo currently doesn't implement the stuff that Jasig added to CAS (and I don't know that the features they added are all that useful to begin with) -- which is why I don't want to use CAS 3.0
Also, using CAS as

**Comment by t3hmrman** [comment]
If there are some specific features in CAS 3.0/4.0 that are really worth including I could definitely consider it again

**Comment by iyee** [comment]
Okay, fair enough.
